language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
addons:
  chrome: stable
  firefox: latest
install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
script:
  - cargo test
  - cd bj-web
  - wasm-pack test --firefox --headless
  - wasm-pack test --chrome  --headless
