[workspace]
members =[
    "bj-core",
    "bj-bin",
    "bj-web/basic-strategy",
    "bj-web/custom-card",
    "bj-web/core",
    "bj-web/counting",
    "bj-web/time-trial",
]

[profile.release]
lto = true
